apiVersion: v1
kind: PersistentVolume
metadata:
  name: amqp-pv
  labels:
    type: amqp-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: amqp-storage-class
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/rabbitmq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amqp-pvc
  labels:
    type: amqp-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: amqp-storage-class
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: amqp-service
  labels:
    version: 1.0.0
    type: amqp-service
spec:
  selector:
    version: 1.0.0
    type: amqp-pod
  ports:
    - protocol: TCP
      port: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqp-deployment
  labels:
    version: 1.0.0
    type: amqp-deployment
spec:
  template:
    metadata:
      name: amqp-pod
      labels:
        version: 1.0.0
        type: amqp-pod
    spec:
      containers:
        - name: amqp-container
          image: firefoxegy/amqp
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: amqp-pv
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: amqp-pv
          persistentVolumeClaim:
            claimName: amqp-pvc
  replicas: 1
  selector:
    matchLabels:
      version: 1.0.0
      type: amqp-pod
