doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be auto-loaded
        'DoctrineMigrations': '%kernel.project_dir%/src/Port/Adapter/Persistence/MySQL/Doctrine/Migration'
