doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            post_id:
                class: App\Port\Adapter\Persistence\MySQL\Doctrine\Type\PostIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Domain\Model:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Port/Adapter/Persistence/MySQL/Doctrine/Mapping'
                prefix: 'App\Domain\Model'
                alias: Domain\Model
