apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-rs
  labels:
    app: myapp
    type: backend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: backend
    spec:
      containers:
        - name: es01
          image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
          environment:
            - node.name=es01
            - discovery.type=single-node
          ulimits:
            memlock:
              soft: -1
              hard: -1
          volumes:
            - data01:/usr/share/elasticsearch/data
          ports:
            - 9200:9200
            - 9300:9300
          hostname: es01

  replicas: 5
  selector:
    matchLabels:
      type: backend
