version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elastic_container
    environment:
      - node.name=es01
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    hostname: es01
    networks:
      - ddd

  db:
    image: mysql:8.0.20
    restart: always
    volumes:
      - db:/var/lib/mysql
    container_name: db_container
    environment:
      - MYSQL_DATABASE=ddd
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - ddd

  nginx:
    build: ./docker/nginx
    container_name: web_container
    volumes_from:
      - php:rw
    volumes:
      - fpm_sockets:/tmp
    depends_on:
      - php
      - es01
      - db
      - redis
    ports:
      - 80:8080
      - 443:8443
    links:
      - db
      - es01
      - php
      - redis
    networks:
      - ddd

  php:
    build: ./docker/php
    container_name: php_fpm_container
    volumes:
      - .:/var/www/html:cached
      - fpm_sockets:/tmp
    networks:
      - ddd
    environment:
      PHP_IDE_CONFIG: "serverName=ddd"

  redis:
    image: redis
    networks:
      - ddd
    hostname: redis
    container_name: redis_container
    ports:
      - 6379:6379

  composer:
    build: ./docker/composer
    container_name: composer_container
    volumes:
      - .:/app
    networks:
      - ddd

volumes:
  data01:
    driver: local
  db:
    driver: local
  fpm_sockets:
    driver: local

networks:
  ddd:
    driver: bridge
