apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    version: 1.0.0
    type: web-service
spec:
  selector:
    version: 1.0.0
    type: web-server-pod
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  labels:
    version: 1.0.0
    type: web-server-deployment
spec:
  template:
    metadata:
      name: web-server-pod
      labels:
        version: 1.0.0
        type: web-server-pod
    spec:
      containers:
        - name: web-container
          image: firefoxegy/nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      version: 1.0.0
      type: web-server-pod
