apiVersion: v1
kind: Service
metadata:
  name: ddd-web-server-service
  labels:
    version: 1.0.0
    type: web-server-service
spec:
  selector:
    version: 1.0.0
    type: web-server-pod
  ports:
    - protocol: TCP
      port: 80