apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddd-web-server-deployment
  labels:
    version: 1.0.0
    type: web-server-deployment
spec:
  template:
    metadata:
      name: ddd-web-server-pod
      labels:
        version: 1.0.0
        type: web-server-pod
    spec:
      containers:
        - name: web-container
          image: firefoxegy/nginx-1.19.4-alpine:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      type: web-server-pod
