services:
  Elasticsearch\ClientBuilder:
    factory: [ 'Elasticsearch\ClientBuilder', 'create' ]
    calls:
      - [ setHosts, [ [ '%env(resolve:ELASTIC_URL)%' ] ] ]
      - [ build ]

  Predis\Client:
    arguments:
      $parameters: '%env(resolve:REDIS_URL)%'