services:
  Elasticsearch\ClientBuilder:
    factory: [ 'Elasticsearch\ClientBuilder', 'create' ]
    calls:
      - [ setHosts, [ [ 'ddd-elastic-service:9200' ] ] ]
      - [ build ]

  Predis\Client:
    arguments:
      $parameters: 'tcp://ddd-redis-service:6379'