services:
  Elasticsearch\ClientBuilder:
    factory: [ 'Elasticsearch\ClientBuilder', 'create' ]
    calls:
      - [ setHosts, [ [ 'es01:9200' ] ] ]
      - [ build ]

  Predis\Client:
    arguments:
      $parameters: 'tcp://redis:6379'