services:
  Elasticsearch\ClientBuilder:
    factory: [ 'Elasticsearch\ClientBuilder', 'create' ]
    calls:
      - [ setHosts, [ [ 'es01:9200' ] ] ]
      - [ build ]

  App\Port\Adapter\UI\Controller\CreatePostController:
    arguments:
      $bus: '@messenger.default_bus'

  App\Application\Command\CreatePostCommandHandler:
    arguments:
      $repository: '@App\Port\Adapter\Persistence\MySQL\DoctrinePostRepository'
      $projector: '@App\Domain\Projector'
      $clientBuilder: 'Elasticsearch\ClientBuilder'

  App\Port\Adapter\Persistence\ElasticSearch\ElasticSearchPostRepository:
    arguments:
      $clientBuilder: 'Elasticsearch\ClientBuilder'
