apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: mysql-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-storage-class
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    type: mysql-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-storage-class
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    version: 1.0.0
    type: mysql-service
spec:
  ports:
    - port: 3306
  selector:
    type: mysql-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    version: 1.0.0
    type: mysql-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      name: mysql-pod
      labels:
        version: 1.0.0
        type: mysql-pod
    spec:
      containers:
        - name: mysql-container
          image: firefoxegy/mysql
          env:
            - name: MYSQL_DATABASE
              value: ddd
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
  replicas: 1
  selector:
    matchLabels:
      version: 1.0.0
      type: mysql-pod
