apiVersion: v1
kind: Service
metadata:
  name: ddd-db-service
  labels:
    version: 1.0.0
    type: mysql-service
spec:
  ports:
    - port: 3306
  selector:
    type: mysql-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddd-mysql-deployment
  labels:
    version: 1.0.0
    type: mysql-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      name: ddd-mysql-pod
      labels:
        version: 1.0.0
        type: mysql-pod
    spec:
      containers:
        - name: mysql-container
          image: firefoxegy/mysql-ddd
          env:
            - name: MYSQL_DATABASE
              value: ddd
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistence-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistence-volume
          persistentVolumeClaim:
            claimName: mysql-pv-claim
  replicas: 1
  selector:
    matchLabels:
      type: mysql-pod
