apiVersion: v1
kind: Service
metadata:
  name: ddd-mysql-service
  labels:
    version: 1.0.0
    type: mysql-service
spec:
  selector:
    version: 1.0.0
    type: mysql-pod
  ports:
    - protocol: TCP
      port: 3306