apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    type: redis-pv-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: redis-storage-class
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  labels:
    type: redis-pv-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: redis-storage-class
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ddd-redis-service
  labels:
    version: 1.0.0
    type: redis-service
spec:
  selector:
    version: 1.0.0
    type: redis-pod
  ports:
    - protocol: TCP
      port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddd-redis-deployment
  labels:
    version: 1.0.0
    type: redis-deployment
spec:
  template:
    metadata:
      name: ddd-redis-pod
      labels:
        version: 1.0.0
        type: redis-pod
    spec:
      containers:
        - name: redis-container
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-persistence-volume
              mountPath: /data
      volumes:
        - name: redis-persistence-volume
          persistentVolumeClaim:
            claimName: redis-pv-claim
  replicas: 1
  selector:
    matchLabels:
      type: redis-pod
