apiVersion: v1
kind: Service
metadata:
  name: ddd-php-fpm-service
  labels:
    version: 1.0.0
    type: php-fpm-service
spec:
  selector:
    version: 1.0.0
    type: php-fpm-pod
  ports:
    - protocol: TCP
      port: 9000