apiVersion: v1
kind: Service
metadata:
  name: ddd-elastic-service
  labels:
    version: 1.0.0
    type: elastic-service
spec:
  selector:
    version: 1.0.0
    type: elastic-pod
  ports:
    - protocol: TCP
      port: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddd-elastic-deployment
  labels:
    version: 1.0.0
    type: elastic-deployment
spec:
  template:
    metadata:
      name: ddd-elastic-pod
      labels:
        version: 1.0.0
        type: elastic-pod
    spec:
      containers:
        - name: elastic-container
          image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: elastic-persistence-volume
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elastic-persistence-volume
          persistentVolumeClaim:
            claimName: elastic-pv-claim
  replicas: 1
  selector:
    matchLabels:
      type: elastic-pod
