apiVersion: v1
kind: Service
metadata:
  name: ddd-elastic-service
  labels:
    version: 1.0.0
    type: elastic-service
spec:
  selector:
    version: 1.0.0
    type: elastic-pod
  ports:
    - protocol: TCP
      port: 9200