apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddd-elastic-deployment
  labels:
    version: 1.0.0
    type: elastic-deployment
spec:
  template:
    metadata:
      name: ddd-elastic-pod
      labels:
        version: 1.0.0
        type: elastic-pod
    spec:
      containers:
        - name: elastic-container
          image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
  replicas: 1
  selector:
    matchLabels:
      type: elastic-pod
