apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-pv-claim
  labels:
    type: elastic-pv-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi