apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv
  labels:
    type: elastic-pv-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: elastic-storage-class
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-pv-claim
  labels:
    type: elastic-pv-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: elastic-storage-class
  resources:
    requests:
      storage: 5Gi