apiVersion: v1
kind: Service
metadata:
  name: ddd-php-fpm-service
  labels:
    version: 1.0.0
    type: php-fpm-service
spec:
  selector:
    version: 1.0.0
    type: php-fpm-pod
  ports:
    - protocol: TCP
      port: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddd-php-fpm-deployment
  labels:
    version: 1.0.0
    type: php-fpm-deployment
spec:
  template:
    metadata:
      name: ddd-php-fpm-pod
      labels:
        version: 1.0.0
        type: php-fpm-pod
    spec:
      containers:
        - name: php-fpm-container
          image: firefoxegy/php
          ports:
            - containerPort: 9000
  replicas: 2
  selector:
    matchLabels:
      type: php-fpm-pod
